spring:
  main:
    allow-circular-references: true
  application:
    name: Trendyol.az
  jpa:
    datasource-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          format_sql: true
  h2:
    console:
      enabled: true